### ISSUE TITLE
using ONBUILD npm install doesn't allow for any yum dependencies to be installed before npm tries to install stuff

### ISSUE THREAD

**Issue by mikeyhu** [UKHomeOffice/docker-nodejs#4]
If one of the NPM packages I want to install has extra YUM dependencies then I don't get the chance to install them before 'npm install' is invoked via the ONBUILD.

Not sure if there is a solution to this other than:
- adding extra required dependencies into this container build
- creating a completely different image similar to this but with my required dependencies

Any other ideas? Am I missing something obvious?
There was an issue raised on Docker about it but doesnt seem to have been implemented:
https://github.com/docker/docker/issues/8240

**Comment by allandegnan** [comment]
We could probably do an ONBUILD RUN "yum install -y $PACKAGES".  I'm not a big fan of that solution but it might work, no?

EDIT:
I tried doing this.  It doesn't work.  I gather from testing that the parent never sees the ENV set in the child.

**Comment by PurpleBooth** [comment]
Not if you need the dependencies to complete the NPM install unfortunately.

**Comment by timgent** [comment]
We now have this:
https://github.com/UKHomeOffice/docker-nodejs-base
For when there is a need to deviate from standard pattern. If there are dependencies that are very common though we shold add them in here. Will close this if no objections
