### ISSUE TITLE
make this not run as root.

### ISSUE THREAD

**Issue by allandegnan** [UKHomeOffice/docker-nodejs#9]
We probably shouldn't really be doing our npm install as root, nor should we be running our apps as root.  I think we need to add a user.  I dare say we should add the user upstream in the centos base and consume a standard user everywhere we want to run non-privilege stuff (pretty much everywhere I guess).  More importantly, adding the user upstream will mean we have the same UID everywhere.

**Comment by timgent** [comment]
https://github.com/UKHomeOffice/docker-nodejs/pull/20
